name: final_project
description: A new Flutter project.
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=3.0.6 <4.0.0"

dependencies:
  blurrycontainer: ^1.0.2
  button_navigation_bar: ^0.1.3
  flutter:
    sdk: flutter
  google_fonts: ^5.1.0
  responsive_navigation_bar: ^4.0.3
  animated_bottom_navigation_bar: ^1.2.0
  dotted_border: ^2.0.0+3
  floating_action_bubble: 1.1.4
  table_calendar: ^3.0.9
  
  modern_form_line_awesome_icons: ^2.0.1

  navbar_router: ^0.6.1
  font_awesome_flutter: ^10.5.0
  lottie: ^2.6.0
  flutter_bloc: ^8.1.3
  image_picker: ^1.0.4
  syncfusion_flutter_pdf: ^20.3.49
  file_picker: ^4.1.4
  open_file: ^3.2.1
  path_provider: ^2.0.11
  supabase_flutter: ^1.10.16
  percent_indicator: ^4.2.3
  shimmer: ^3.0.0
  animated_text_kit: ^4.2.2
  elegant_notification: ^1.11.1
  animated_splash_screen: ^1.3.0
  syncfusion_flutter_calendar: ^20.4.54
  intl: ^0.18.1


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/Images/
    - assets/Images/1434020125875430376profile-hi.png
    - assets/
  fonts:
    - family: prata
      fonts:
        - asset: assets/font/Prata-Regular.ttf
    - family: Tajawal
      fonts:
        - asset: assets/font/Tajawal-Medium.ttf
